name: projet_flutter
description: "Application de gestion de commandes pour cantine universitaire"

# Empêche la publication accidentelle sur pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase 
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7

  # State Management
  provider: ^6.1.5

  # Utils
  intl: ^0.19.0

  # Icons iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Décommentez si vous ajoutez des assets (images, etc.)
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Décommentez si vous ajoutez des polices personnalisées
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700