// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARqeihbTKliMmCdir3GUJXG7l1qEvKcGQ',
    appId: '1:97135775012:web:507365015726a6c877f7b1',
    messagingSenderId: '97135775012',
    projectId: 'cantineesmt',
    authDomain: 'cantineesmt.firebaseapp.com',
    storageBucket: 'cantineesmt.firebasestorage.app',
    measurementId: 'G-FNLEN2JJYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIIcJBKr8f7vEUbkygiYwbAJLfShCXM_A',
    appId: '1:97135775012:android:136e402626b7813677f7b1',
    messagingSenderId: '97135775012',
    projectId: 'cantineesmt',
    storageBucket: 'cantineesmt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC772e_HgIQHLLzz0bgwQy6KQOMACcpmkc',
    appId: '1:97135775012:ios:8376aea54b1aa30b77f7b1',
    messagingSenderId: '97135775012',
    projectId: 'cantineesmt',
    storageBucket: 'cantineesmt.firebasestorage.app',
    iosClientId: '97135775012-7ovp6l8f3tu8gb3ibt8s8390n3uc26ot.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC772e_HgIQHLLzz0bgwQy6KQOMACcpmkc',
    appId: '1:97135775012:ios:8376aea54b1aa30b77f7b1',
    messagingSenderId: '97135775012',
    projectId: 'cantineesmt',
    storageBucket: 'cantineesmt.firebasestorage.app',
    iosClientId: '97135775012-7ovp6l8f3tu8gb3ibt8s8390n3uc26ot.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARqeihbTKliMmCdir3GUJXG7l1qEvKcGQ',
    appId: '1:97135775012:web:37d160ab9b79de1577f7b1',
    messagingSenderId: '97135775012',
    projectId: 'cantineesmt',
    authDomain: 'cantineesmt.firebaseapp.com',
    storageBucket: 'cantineesmt.firebasestorage.app',
    measurementId: 'G-KTWECD4MD9',
  );
}
